all:
	cd e1000-8.0.35-DNA/src; make
	cd e1000e-2.0.0-DNA/src; make
	cd igb-3.4.7-DNA/src; make
	cd ixgbe-3.7.17-DNA/src; make

clean:
	cd e1000-8.0.35-DNA/src; make clean
	cd e1000e-2.0.0-DNA/src; make clean
	cd igb-3.4.7-DNA/src; make clean
	cd ixgbe-3.7.17-DNA/src; make clean

