E1000=e1000/e1000-8.0.35
E1000E=e1000e/e1000e-2.5.4-zc
IGB=igb/igb-5.0.6-zc
IXGBE=ixgbe/ixgbe-3.18.7-zc

all:
#	cd $(E1000)/src; make
#	cd $(E1000E)/src; make
	cd $(IGB)/src; make
	cd $(IXGBE)/src; make

clean:
#	cd $(E1000)/src; make clean
#	cd $(E1000E)/src; make clean
	cd $(IGB)/src; make clean
	cd $(IXGBE)/src; make clean
