#! /bin/bash
#
# (C) 2003-13 - ntop.org
#
### BEGIN INIT INFO
# Provides:          pf_ring
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop pf_ring web
### END INIT INFO


start_pf_ring() {
    KERNEL_VERSION=$(uname -r)

    insmod /lib/modules/$KERNEL_VERSION/kernel/net/pf_ring/pf_ring.ko

    DNA_DRIVERS="$(/bin/ls /usr/local/pfring/drivers/DNA/|cut -d '.' -f 1)"
    for D in $DNA_DRIVERS ; do
	DRIVER_CONFIG="/etc/pf_ring/dna-$D.conf"
	if [ -f $DRIVER_CONFIG ]; then
	    PARAM="$(cat $DRIVER_CONFIG)"
	    # Remove the driver first as the original vanilla driver might be the one we want to overwrite
	    /sbin/rmmod $D
	    /sbin/insmod /usr/local/pfring/drivers/DNA/$D.ko $PARAM
	    fi
    done

    # /sbin/ifup -a
    
    # Enable all interfaces DNA and non DNA
    INTERFACES="$(cat /proc/net/dev | grep ':' | cut -d ':' -f 1|grep -v 'lo' | tr -d '\n' | sed 's/^  //'| sed 's/  / /')"
    for D in $INTERFACES ; do
	/sbin/ifconfig $D up
    done
}


stop_pf_ring() {
    DNA_DRIVERS="$(/bin/ls /usr/local/pfring/drivers/DNA/|cut -d '.' -f 1)"
    for D in $DNA_DRIVERS ; do
	DRIVER_CONFIG="/etc/pf_ring/dna-$D.conf"
	if [ -f $DRIVER_CONFIG ]; then
	    /sbin/rmmod $D
	fi
    done

    /sbin/rmmod pf_ring
}

########

INTERFACE_NAME=$2

case "$1" in
  start)
	start_pf_ring;
	;;

  stop)
       	stop_pf_ring;
	;;

  restart)
        stop_pf_ring;
	start_pf_ring;
	;;

  *)
	echo "Usage: /etc/init.d/pf_ring {start|stop|restart}"
	exit 1
esac

exit 0
